services:
  - type: web
    name: r3f-immersive-explorer
    env: node
    buildCommand: bash render-build.sh
    startCommand: npm start
    port: 10000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.x
