services:
  - type: web
    name: r3f-immersive-explorer
    env: static
    buildCommand: bash render-build.sh
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.x
